let contentData = [
    {
    id: "p_1",
    img: "/images/phone-1.jpg" ,
    name: "phone",
    desc:"Lorem ipsum dolor sit amet consectetur.",
    price: 150,
},
    {
    id: "l_1",
    img: "/images/laptop-2.jpg",
    name: "laptop",
    desc: "Lorem ipsum dolor sit amet consectetur.",
    price: 580,
},
    {
    id: "a_1",
    img: "/images/watch-3.jpg",
    name: "watch",
    desc: "Lorem ipsum dolor sit amet consectetur.",
    price: 80,
}, 
    {
    id: "a_2",
    img: "/images/pad-4.jpg",
    name: "gaming pad",
    desc: "Lorem ipsum dolor sit amet consectetur.",
    price: 35,
},
    {
    id: "g_1",
    img: "/images/board-5.jpg",
    name: "motherboard",
    desc: "Lorem ipsum dolor sit amet consectetur.",
    price: 130,
},
    {
    id: "g_2",
    img: "/images/board-5.jpg",
    name: "new model mother 5",
    desc: "Lorem ipsum dolor sit amet consectetur.",
    price: 800,
},
    {
    id: "p_2",
    img: "/images/phone-6.jpg",
    name: "another phone",
    desc: "Lorem ipsum dolor sit amet consectetur.",
    price: 270,
}];